services:
  # 1. Główny silnik OpenVAS (Greenbone)
  openvas-master:
    image: immauss/openvas:latest
    container_name: openvas-master
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - openvas_data:/data
    environment:
      - PASSWORD=admin123 # Hasło dla użytkownika admin w GVM

  # 2. Serwer SSH (Tunele dla sensorów)
  tunnel-server:
    image: linuxserver/openssh-server:latest
    container_name: tunnel-server
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=scanner_user
      - PASSWORD_ACCESS=false
      - SUDO_ACCESS=false
      - LISTEN_PORT=2222
#      - PUBLIC_KEY_FILE=/config/authorized_keys
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
      - ALLOW_TCP_FORWARDING=true
      - GATEWAY_PORTS=true
    volumes:
      - ./remote_keys/authorized_keys:/config/.ssh/authorized_keys
    restart: unless-stopped

  # 3. API Rejestrujące (Dodaje skanery i aktualizuje config)
  registrar:
    build: ./registrar
    container_name: registrar
    network_mode: host
    environment:
      - GVM_USER=admin
      - GVM_PASS=admin123
      - GVM_HOST=127.0.0.1
    volumes:
      - ./remote_keys/authorized_keys:/config/.ssh/authorized_keys

      - ./shared_config:/app/shared_config # config.yaml i ports.txt
    depends_on:
      - openvas-master

  # 4. Orchestrator (Demon wysyłający raporty)
  orchestrator:
    build: ./orchestrator
    container_name: scan-orchestrator
    network_mode: host
    environment:
      - GVM_USER=admin
      - GVM_PASS=admin123
      - GVM_HOST=127.0.0.1
    volumes:
      - ./orchestrator/reports:/app/reports
      - ./shared_config:/app/shared_config
    restart: unless-stopped
    depends_on:
      - registrar

volumes:
  openvas_data:
    external: true